export const DUMMY_ACTIVITY = [
  {
    id: 1,
    activity: "Weights",
    date: "11/28/2022",
    duration: 1,
    notes: "Upper 1",
  },
  {
    id: 2,
    activity: "Gi BJJ",
    date: "11/29/2022",
    duration: 1,
    notes: "Collar choke / chasing the back",
  },
  {
    id: 3,
    activity: "No Gi",
    date: "11/29/2022",
    duration: 1,
    notes: "Guillotines from headstrap, high elbow/push variation",
  },
  {
    id: 4,
    activity: "Weights",
    date: "11/30/2022",
    duration: 1,
    notes: "Lower 2",
  },
  {
    id: 5,
    activity: "No Gi",
    date: "12/1/2022",
    duration: 1,
    notes:
      "Attacking 1/4 guard 1) w/ shallow underhook and crossface 2) backstep to saddle heel hook 3) backstep to saddle double trouble",
  },
  {
    id: 6,
    activity: "Gi BJJ",
    date: "12/1/2022",
    duration: 1,
    notes: "Pin one leg and jump and leg drag other leg / leg drag defense",
  },
  {
    id: 7,
    activity: "Gi BJJ",
    date: "12/3/2022",
    duration: 1,
    notes: "Open mat",
  },
  {
    id: 8,
    activity: "Gi BJJ",
    date: "12/12/2022",
    duration: 1,
    notes: "DLR w/ pants grip to shin on shin. 1) standup/take pant/collar grip take down 2) single leg x",
  },
  {
    id: 9,
    activity: "Gi BJJ",
    date: "12/13/2022",
    duration: 1,
    notes: "1) Breaking spider-lasso guard to throw by. 2) when opponent granbys stack leg drag to x hook backtake",
  },
  {
    id: 10,
    activity: "No Gi",
    date: "12/13/2022",
    duration: 1,
    notes: "false reap sweep to saddle then heel hook. loose passing",
  },
  {
    id: 11,
    activity: "No Gi",
    date: "12/14/2022",
    duration: 1,
    notes: "shin on shin to DLR. finishing option side sweep knockdown or caio terra ankle lock. Injured thumb",
  },
  {
    id: 12,
    activity: "Weights",
    date: "12/18/2022",
    duration: 1,
    notes: "Upper 1. Bench 22.5kg 3x5",
  },
  {
    id: 13,
    activity: "Weights",
    date: "12/19/2022",
    duration: 1,
    notes: "Lower 1. Squat 30kg 3x5",
  },
  {
    id: 14,
    activity: "Gi BJJ",
    date: "12/19/2022",
    duration: 1,
    notes: "DLR pass using kicking back and across to remove the hook to torreando",
  },
  {
    id: 15,
    activity: "Gi BJJ",
    date: "12/20/2022",
    duration: 1,
    notes: "DLR pass using kicking back and across to remove the hook to torreando",
  },
  {
    id: 16,
    activity: "Gi BJJ",
    date: "12/20/2022",
    duration: 1,
    notes: "passing sitting guard. collar grip knee cut. weave the leg torreando. diving kimura.",
  },
  {
    id: 17,
    activity: "No Gi",
    date: "12/20/2022",
    duration: 1,
    notes: "Leg drag to saddle. leg weave pass, underhook counter to darce.",
  }
];

export const GYM_DATA = [
  {
    id: 1,
    name: "Kaizen MMA Fairfax",
    notes: "Started BJJ here in Mar 2018",
    loc: "Fairfax, VA USA",
    type: "main",
    website: "https://kzmma.com/",
  },
  {
    id: 2,
    name: "Kaizen MMA Vienna",
    notes: "Trained here frequently on days Fairfax did not have classes",
    loc: "Vienna, VA USA",
    type: "secondary",
    website: "https://kzmma.com/",
  },
  {
    id: 3,
    name: "AKA Sunnyvale",
    notes: "Drop in - 1 day",
    loc: "Sunnyvale, CA USA",
  },
  {
    id: 4,
    name: "Impacto Osaka",
    notes: "Drop in - 2 days",
    loc: "Sakai, Osaka Japan",
  },
  {
    id: 5,
    name: "Pure Performance Martial Arts Center",
    notes: "Lachlan Giles seminar",
    loc: "Rockville, MD USA",
  },
  {
    id: 6,
    name: "10th Planet Jiu Jitsu Downtown Los Angeles",
    notes: "Drop in - 2 day",
    loc: "Los Angeles, CA USA",
  },
  {
    id: 7,
    name: "Vanguard Gym",
    notes: "Participated in tournament",
    loc: "Manassas, VA USA",
  },
  {
    id: 8,
    name: "Abmar Barbosa Jiu Jitsu Academy",
    notes:
      "Started training here in Jan 2020. Stopped due to COVID. Returned in April 2021.",
    loc: "Vienna, VA USA",
    type: "main",
  },
  {
    id: 9,
    name: "UFC Gym Fairfax",
    notes: "Drop in - 1 day",
    loc: "Fairfax, VA USA",
  },
  {
    id: 10,
    name: "Fifty/50 Martial Arts Academy",
    notes: "drop in 1 day",
    loc: "Falls Church, VA USA",
  },
  {
    id: 11,
    name: "Silverback Academy",
    notes: "Drop in - 1 day",
    loc: "Chantilly, VA USA",
  },
  {
    id: 12,
    name: "Marcelo Garcia Jiu-Jitsu Academy",
    notes: "Drop in - 1 day",
    loc: "New York City, NY USA",
  },
  {
    id: 13,
    name: "Carpe Diem Hiroo",
    notes: "Started training here in May 2022",
    loc: "Minato City, Tokyo Japan",
    type: "main",
    website: "https://hiroo.carpediembjj.tokyo/",
  },
  {
    id: 14,
    name: "Carpe Diem Jiyugaoaka",
    notes: "Train here on Tuesdays",
    loc: "Meguro City, Tokyo Japan",
    type: "secondary",
    website: "https://jiyugaoka.carpediembjj.tokyo/"
  },
];

export const COMP_RECORD = [
  {
    id: 1,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "No Gi - Novice",
    weightClass: "Feather",
    weight: "149",
    result: "W",
    method: "Armbar",
  },
  {
    id: 2,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "No Gi - Novice",
    weightClass: "Feather",
    weight: "149",
    result: "L",
    method: "Guillotine Choke",
  },
  {
    id: 3,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "149",
    result: "W",
    method: "Armbar",
  },
  {
    id: 4,
    name: "US Grappling Richmond",
    date: "4/27/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "149",
    result: "W",
    method: "Points",
  },
  {
    id: 5,
    name: "Vanguard Battle Royal Beginner + Intermediate Sub-Only Fall Tournament",
    date: "9/28/19",
    division: "No Gi - Beginner",
    weightClass: "Light",
    weight: "155",
    result: "W",
    method: "Darce Choke",
  },
  {
    id: 6,
    name: "Vanguard Battle Royal Beginner + Intermediate Sub-Only Fall Tournament",
    date: "9/28/19",
    division: "No Gi - Beginner",
    weightClass: "Light",
    weight: "155",
    result: "W",
    method: "Triangle Choke",
  },
  {
    id: 7,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "W",
    method: "Walkover",
  },
  {
    id: 8,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "W",
    method: "Points",
  },
  {
    id: 9,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "L",
    method: "Decision",
  },
  {
    id: 10,
    name: "COPA Virgnia - Fall 2019",
    date: "10/28/19",
    division: "Gi - White Belt",
    weightClass: "Feather",
    weight: "154.5",
    result: "L",
    method: "Armbar",
  },
];
