import Link from "next/link";
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHouse,
  faChartLine,
  faDumbbell,
  faMedal,
} from "@fortawesome/free-solid-svg-icons";

import styles from "./Layout.module.css";

type Layout = {
  children: any;
};

const Layout = ({ children }: Layout) => {
  return (
    <div>
      <Head>
        <title>Fit Log</title>
        <meta
          name="Tool to visually log my exercise progress/activity"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <Link href="/">
          <FontAwesomeIcon icon={faHouse} />
        </Link>
        <Link href="/activity">
          <FontAwesomeIcon icon={faChartLine} />
        </Link>
        <Link href="/gyms">
          <FontAwesomeIcon icon={faDumbbell} />
        </Link>
        <Link href="/achievements">
          <FontAwesomeIcon icon={faMedal} />
        </Link>
      </nav>
      {children}
      <a
        className={styles.footer}
        href="https://timleevt.github.io"
        target="_blank"
        rel="noreferrer"
      >
        timleevt.github.io
      </a>
    </div>
  );
};

export default Layout;
